name: tasker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  equatable: ^2.0.7
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^1.4.0
  path_provider: ^2.1.5
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

